// flow-typed signature: 3869b6376de58d244d309dce6687d5a9
// flow-typed version: <<STUB>>/font-face_v^2.3.1/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'font-face'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'font-face' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'font-face/index' {
  declare module.exports: $Exports<'font-face'>;
}
declare module 'font-face/index.js' {
  declare module.exports: $Exports<'font-face'>;
}
